Vendor licenses
PelionIoT/kube-router pull request #3
Opened 2021-04-22 05:34 UTC by sk-arm

Created vendor license file for legal approval for make the repo public.

2021-04-22 09:57 UTC, ZakariasL requested changes

2021-04-22 09:57 UTC, ZakariasL commented on vendor-licenses.txt
> +party software included in this release of 'edge-proxy'.
Replace `edge-proxy` with `kube-router`

2021-04-22 09:57 UTC, ZakariasL commented on vendor-licenses.txt
> +Refer to the License Agreement that accompanies this release of 'edge-proxy'
Same as above

2021-04-22 17:36 UTC, sk-arm commented on vendor-licenses.txt
> +party software included in this release of 'edge-proxy'.
Changed to PelionIoT/kube-router.

2021-04-22 17:36 UTC, sk-arm commented on vendor-licenses.txt
> +Refer to the License Agreement that accompanies this release of 'edge-proxy'
Changed to PelionIoT/kube-router.

2021-04-23 09:03 UTC, ZakariasL approved these changes
LGTM

2021-04-23 14:52 UTC, merged